# Application
spring.application.name=golden-raspberry-api
server.port=8080

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:goldenraspberrydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=YEAR
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# H2 Console (optional, useful for inspection)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# CSV file path
app.csv.file-path=movielist.csv
